/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import controls.JMyButton;
import controls.JTextBox;
import entity.Abteilung;
import entity.AngestelltPhones;
import entity.Angestellte;
import firma.Tools;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author insaa
 */
public class frmAngetstellte extends javax.swing.JFrame {

    /**
     * Creates new form frmAngetstellte
     */
    public frmAngetstellte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup = new javax.swing.ButtonGroup();
        btnBack = new controls.JMyButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtName = new JTextBox(15);
        txtAdresse = new JTextBox(15);
        txtGehalt = new JTextBox(15);
        txtEinstellungsDate = new com.toedter.calendar.JDateChooser();
        txtGeburtsDatum = new com.toedter.calendar.JDateChooser();
        cbxAbteilung = new controls.JMyCombo();
        btnAdd = new controls.JMyButton();
        btnNeu = new controls.JMyButton();
        btnUpdate = new controls.JMyButton();
        btnDelete = new controls.JMyButton();
        btnFind = new controls.JMyButton();
        btnAll = new controls.JMyButton();
        jLabel9 = new javax.swing.JLabel();
        rdoNummer = new javax.swing.JRadioButton();
        rdoName = new javax.swing.JRadioButton();
        rdoAdresse = new javax.swing.JRadioButton();
        rdoGehalt = new javax.swing.JRadioButton();
        rdoGeburtsDatum = new javax.swing.JRadioButton();
        rdoEinstellung = new javax.swing.JRadioButton();
        rdoAbteilung = new javax.swing.JRadioButton();
        txtNummber = new JTextBox(15);
        txtSuchen = new JTextBox(50);
        btnSuchen = new controls.JMyButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAngestellte = new javax.swing.JTable();
        btnAddAbteilung = new controls.JMyButton();
        jLabel10 = new javax.swing.JLabel();
        txtTelefon = new JTextBox(15);
        btnAddTelefon = new controls.JMyButton();
        btnDeleteAllTelefon = new controls.JMyButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTelefon = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnBack.setText("Zurück");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Angestellte Form");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Name:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nummer:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Adresse:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Gehalt:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("einstellungsdatum:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Geburtsdatum:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Abteilung:");

        btnAdd.setText("Hinzufügen");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnNeu.setText("Neu");
        btnNeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNeuActionPerformed(evt);
            }
        });

        btnUpdate.setText("Ändern");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Löschen");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnFind.setText("Finden");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnAll.setText("Alle ");
        btnAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAllActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Suchen nach:");

        rdoNummer.setBackground(new java.awt.Color(255, 255, 255));
        rdoNummer.setSelected(true);
        rdoNummer.setText("Nummer");

        rdoName.setBackground(new java.awt.Color(255, 255, 255));
        rdoName.setText("Name");

        rdoAdresse.setBackground(new java.awt.Color(255, 255, 255));
        rdoAdresse.setText("Adresse");

        rdoGehalt.setBackground(new java.awt.Color(255, 255, 255));
        rdoGehalt.setText("Gehalt");

        rdoGeburtsDatum.setBackground(new java.awt.Color(255, 255, 255));
        rdoGeburtsDatum.setText("Geburtstag");

        rdoEinstellung.setBackground(new java.awt.Color(255, 255, 255));
        rdoEinstellung.setText("Einstellung");

        rdoAbteilung.setBackground(new java.awt.Color(255, 255, 255));
        rdoAbteilung.setText("Abteilung");

        txtNummber.setEditable(false);

        btnSuchen.setText("Suchen");
        btnSuchen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuchenActionPerformed(evt);
            }
        });

        tblAngestellte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nummer ", "Name", "Adresse", "Gehalt", "Einstellungsdatum", "Geburtsdatum", "Abteilungsnummer", "Abteilungsname"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAngestellte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAngestellteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblAngestellte);

        btnAddAbteilung.setText("+");
        btnAddAbteilung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAbteilungActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("TelefonNummer:");

        btnAddTelefon.setText("Telefonnummer hinzfügen");
        btnAddTelefon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTelefonActionPerformed(evt);
            }
        });

        btnDeleteAllTelefon.setText("Telefonnummern löscen");
        btnDeleteAllTelefon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAllTelefonActionPerformed(evt);
            }
        });

        tblTelefon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Telefonnummer"
            }
        ));
        jScrollPane2.setViewportView(tblTelefon);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNeu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(btnDeleteAllTelefon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAddTelefon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtGehalt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNummber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbxAbteilung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtGeburtsDatum, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                                            .addComponent(txtEinstellungsDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addComponent(btnAddAbteilung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(rdoNummer)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdoName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdoAdresse)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdoGehalt)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdoEinstellung)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdoGeburtsDatum)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdoAbteilung))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtSuchen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnSuchen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(rdoNummer)
                            .addComponent(rdoName)
                            .addComponent(rdoAdresse)
                            .addComponent(rdoGehalt)
                            .addComponent(rdoGeburtsDatum)
                            .addComponent(rdoEinstellung)
                            .addComponent(rdoAbteilung))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSuchen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSuchen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtGehalt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(txtNummber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtEinstellungsDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtGeburtsDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cbxAbteilung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(btnAddAbteilung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDeleteAllTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNeu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        
        try {
            this.dispose();
            Tools.openForm(new frmMain());
        } catch (IOException ex) {
            Logger.getLogger(frmAngetstellte.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnBackActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        btnGroup.add(rdoNummer);
        btnGroup.add(rdoName);
        btnGroup.add(rdoAdresse);
        btnGroup.add(rdoGehalt);
        btnGroup.add(rdoEinstellung);
        btnGroup.add(rdoGeburtsDatum);
        btnGroup.add(rdoAbteilung);
        
        datenbank.go.fillCompo("abteilung", "abteilungsname", cbxAbteilung);
        newData();
        Emp.getAllRows(tblAngestellte);
        tblAngestellte.getTableHeader().setReorderingAllowed(false);
    }//GEN-LAST:event_formWindowOpened
    Angestellte Emp = new Angestellte();
    Abteilung dept = new Abteilung();
    private void btnAddAbteilungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAbteilungActionPerformed
        int AbteilungsNummer = Integer.parseInt(dept.getAutoNumber());
        String AbteilungsName = (String)Tools.inputBox("Bitte den Name der Abteilung eingeben.");
        String Ort = (String)Tools.inputBox("Bitte die Ort der Abteilung eingeben.");
        dept.setAbteilungsId(AbteilungsNummer);
        if(AbteilungsName == "" || AbteilungsName ==null 
        || Ort =="" || Ort == null){
            Tools.messageBox("Bitte alle Felder ausfüllen.");
            return;
        }
        else{
           dept.setAbteilungsName(AbteilungsName);
           dept.setOrt(Ort);
           dept.add(); 
           datenbank.go.fillCompo("abteilung", "abteilungsname", cbxAbteilung);
        }
    }//GEN-LAST:event_btnAddAbteilungActionPerformed

    private void newData(){
        Tools.clearText(this);
        txtNummber.setText(Emp.getAutoNumber());
        btnAdd.setEnabled(true);
        btnDelete.setEnabled(false);
        btnUpdate.setEnabled(false);
        btnDeleteAllTelefonActionPerformed(null);
        txtName.requestFocus();
   }
    
    private void btnNeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNeuActionPerformed
        newData();
    }//GEN-LAST:event_btnNeuActionPerformed
   
    private void setValues(){
         Emp.setAngetellteId(Integer.parseInt(txtNummber.getText()));
         Emp.setName(txtName.getText());
         Emp.setAdresse(txtAdresse.getText());
         Emp.setGehalt(Double.parseDouble(txtGehalt.getText()));
         
         SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
         
         String EinDate = String.valueOf(f.format(txtEinstellungsDate.getDate()));
         String GebDate = String.valueOf(f.format(txtGeburtsDatum.getDate()));
         
         Emp.setEinstellungsDate(EinDate);
         Emp.setGeburtstag(GebDate);
         String AbteilungName = cbxAbteilung.getSelectedItem().toString();
         String AbteilungNummer = dept.getValueByName(AbteilungName);
         Emp.setAbteilungsId(Integer.parseInt(AbteilungNummer));
    }
    AngestelltPhones Phon = new AngestelltPhones();
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        setValues();
        Emp.add();
        
        Phon.setAngestellteId(Integer.parseInt(txtNummber.getText()));
        for(int i=0 ; i < tblTelefon.getRowCount(); i++){
            Phon.setPhone(tblTelefon.getValueAt(i, 0).toString());
            Phon.add();
        }
        
        newData();
        Emp.getAllRows(tblAngestellte);
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        setValues();
        Emp.update();
        
        Phon.setAngestellteId(Integer.parseInt(txtNummber.getText()));
        
        Phon.deleteByAngestellte();
        
        for(int i=0 ; i < tblTelefon.getRowCount(); i++){
            Phon.setPhone(tblTelefon.getValueAt(i, 0).toString());
            Phon.add();
        }
        newData();
        Emp.getAllRows(tblAngestellte);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        if(Tools.confirmMesseg("Möchten Sie den Datensatz löschen?")){
            Phon.setAngestellteId(Integer.parseInt(txtNummber.getText()));
            Phon.deleteByAngestellte();
            setValues();
            Emp.delete();
            newData();
            Emp.getAllRows(tblAngestellte);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        String AngestellteNummer = (String) Tools.inputBox("Bitte die Nummer von dem Angestellte eingeben");
        int nummer = Integer.parseInt(AngestellteNummer);
        Emp.setAngetellteId(nummer);
        Emp.getOneRow(tblAngestellte);
        
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAllActionPerformed
        Emp.getAllRows(tblAngestellte);
    }//GEN-LAST:event_btnAllActionPerformed

    private void tblAngestellteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAngestellteMouseClicked
        try{
            int row = tblAngestellte.getSelectedRow();
            txtNummber.setText(tblAngestellte.getValueAt(row, 0).toString());
            txtName.setText(tblAngestellte.getValueAt(row, 1).toString());
            txtAdresse.setText(tblAngestellte.getValueAt(row, 2).toString());
            txtGehalt.setText(tblAngestellte.getValueAt(row, 3).toString());
            SimpleDateFormat f = new SimpleDateFormat("yyyy-MM-dd");
         
            Date EinDate = f.parse(tblAngestellte.getValueAt(row, 4).toString());
            Date GebDate = f.parse(tblAngestellte.getValueAt(row, 5).toString());
            txtEinstellungsDate.setDate(EinDate);
            txtGeburtsDatum.setDate(GebDate);
            cbxAbteilung.setSelectedItem(tblAngestellte.getValueAt(row, 7).toString());
            
            Phon.setAngestellteId(Integer.parseInt(txtNummber.getText()));
            Phon.getAllRows(tblTelefon);
            
            btnAdd.setEnabled(false);
            btnUpdate.setEnabled(true);
            btnDelete.setEnabled(true);
        }
        catch(Exception ex){
            Tools.messageBox(ex.getMessage());
        }
    }//GEN-LAST:event_tblAngestellteMouseClicked
    String strSuchen;
    private String getSuch(String suchNach,String suchWort){
         strSuchen = String.format("select * from angestellte_data where %s like ", suchNach) ;
         strSuchen += "'%" +suchWort +"%'";
        return strSuchen;
    }
    
    private void btnSuchenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuchenActionPerformed
        if(rdoNummer.isSelected() ){
           getSuch("angestellte_Nummer",txtSuchen.getText());
        }
        else if(rdoName.isSelected()){
            getSuch("name",txtSuchen.getText());
        }
        else if(rdoAdresse.isSelected()){
            getSuch("adresse",txtSuchen.getText());
        }
        else if(rdoGehalt.isSelected()){
            getSuch("gehalt",txtSuchen.getText());
        }
        else if(rdoEinstellung.isSelected()){
            getSuch("einstellung_Date",txtSuchen.getText());
        }
        else if(rdoEinstellung.isSelected()){
            getSuch("Geburtstag",txtSuchen.getText());
        }
        else if(rdoGeburtsDatum.isSelected()){
            getSuch("Geburtstag",txtSuchen.getText());
        }
        else if(rdoAbteilung.isSelected()){
            getSuch("abteilung",txtSuchen.getText());
        }
        
        Emp.getCustomRows(strSuchen, tblAngestellte);
    }//GEN-LAST:event_btnSuchenActionPerformed

    private void btnAddTelefonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddTelefonActionPerformed
        DefaultTableModel mod = (DefaultTableModel) tblTelefon.getModel();
        mod.addRow(new Object[]{txtTelefon.getText()});
        txtTelefon.setText("");
        txtTelefon.requestFocus();
    }//GEN-LAST:event_btnAddTelefonActionPerformed

    private void btnDeleteAllTelefonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAllTelefonActionPerformed
        DefaultTableModel mod = (DefaultTableModel) tblTelefon.getModel();
        mod.setNumRows(0);
    }//GEN-LAST:event_btnDeleteAllTelefonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAngetstellte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAngetstellte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAngetstellte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAngetstellte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAngetstellte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private controls.JMyButton btnAdd;
    private controls.JMyButton btnAddAbteilung;
    private controls.JMyButton btnAddTelefon;
    private controls.JMyButton btnAll;
    private controls.JMyButton btnBack;
    private controls.JMyButton btnDelete;
    private controls.JMyButton btnDeleteAllTelefon;
    private controls.JMyButton btnFind;
    private javax.swing.ButtonGroup btnGroup;
    private controls.JMyButton btnNeu;
    private controls.JMyButton btnSuchen;
    private controls.JMyButton btnUpdate;
    private controls.JMyCombo cbxAbteilung;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdoAbteilung;
    private javax.swing.JRadioButton rdoAdresse;
    private javax.swing.JRadioButton rdoEinstellung;
    private javax.swing.JRadioButton rdoGeburtsDatum;
    private javax.swing.JRadioButton rdoGehalt;
    private javax.swing.JRadioButton rdoName;
    private javax.swing.JRadioButton rdoNummer;
    private javax.swing.JTable tblAngestellte;
    private javax.swing.JTable tblTelefon;
    private javax.swing.JTextField txtAdresse;
    private com.toedter.calendar.JDateChooser txtEinstellungsDate;
    private com.toedter.calendar.JDateChooser txtGeburtsDatum;
    private javax.swing.JTextField txtGehalt;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtNummber;
    private javax.swing.JTextField txtSuchen;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration//GEN-END:variables
}
